spring:
  sql:
    init:
      mode: always

  rabbitmq:
    host: localhost:8080
    username: admin
    password: admin
    port: 5672

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

accounterio:
  url: "https://localhost:8080/api/v1/processor"

ai:
  api-key: 00f