spring:
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:h2:file:./receiptAI-h2-database
    username: u
    password: 1

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  rabbitmq:
    host: localhost:8080
    username: admin
    password: admin
    port: 5672

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

accounterio:
  url: "https://localhost:8080/api/v1/processor"

ai:
  api-key: 00f