spring:
  sql:
    init:
      mode: always

  docker:
    compose:
      enabled: true
      skip:
        in-tests: true # test containers used
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: 5672