name: Accounter.io
run-name: Accounter.io pipeline
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test-env
    steps:
      - name: init
        uses: actions/checkout@v3
      - name: set Up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: run tests
        run: mvn test

  integrationTest:
    runs-on: self-hosted
    needs: test
    environment: test-env
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Stop containers
        run: docker compose docker/test/compose.yaml stop
      - name: Clear data
        run: docker system prune
      - name: compose
        run: docker compose docker/test/compose.yaml up -d

  deployment:
    runs-on: self-hosted
    needs: test
    environment: test-env
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Stop containers
        run: docker compose stop
      - name: Clear data
        run: docker system prune
      - name: compose
        run: docker compose up -d